chore: restructure to monorepo
farhan-helmy/uploadje pull request #1
Opened 2023-10-05 15:39 UTC by khairulhaaziq

* chore: restructure to monorepo
* chore: initialize remix frontend

2023-10-06 01:57 UTC, farhan-helmy approved these changes

2023-10-10 05:36 UTC, Xavier-IV requested changes
Great effort brotha!

Left small comments, esp. the logs. Take a look when you're free.

Thanks again!

2023-10-10 05:36 UTC, Xavier-IV commented on README.md
Can you help to share in the Readme some basic setup + requirement, so we can contribute?

Notice the frontend readme which is great, it'll be helpful if its mentioned in the root as this is where user/contributor first see.

Appreciate the huge effort! 🎊

2023-10-10 05:36 UTC, Xavier-IV commented on backend/src/config/logs/app.log
This might not be intended commit?

Best to add in gitignore. To retain the `logs` folder, add `.keep`

e.g. `/logs/.keep`

So that the folder will still exists for log and won't throw "folder does not exists".

2023-10-10 07:31 UTC, khairulhaaziq commented on README.md
sorry ni dah stale sebenarnya. aku work on kat new branch #9 . jap aku add readme situ

2023-10-10 08:09 UTC, Xavier-IV commented on README.md
Mantap, thank you!

2023-11-29 13:18 UTC, closed without merging